### ISSUE TITLE
Tests are trying to write to /usr/lib/python3.6/site-packages/

### ISSUE THREAD

**Issue by cryptomilk** [kvas-it/pytest-console-scripts#11]
Tests are trying to write to /usr/lib/python3.6/site-packages/ and get: Permission denied.

I think they need to be adapted to not write to the directory they are executed in ...

See:
https://build.opensuse.org/package/show/home:gladiac/python-pytest-console-scripts

Log:
https://build.opensuse.org/package/live_build_log/home:gladiac/python-pytest-console-scripts/openSUSE_Tumbleweed/x86_64

**Comment by kvas-it** [comment]
Yes, this sounds like an error in design of the tests. All writing should be in temporary directories.

**Comment by kvas-it** [comment]
I did some initial investigation (see [here](https://github.com/kvas-it/pytest-console-scripts/issues/7#issuecomment-399024944)) and I have half of a plan of how to fix it. Any advice would be welcome.

**Comment by cryptomilk** [comment]
Any news?

**Comment by kvas-it** [comment]
I didn't get any better advice than to use pytest-virtualenv. I will try rewriting the tests to use this hopefully this week.

**Comment by cryptomilk** [comment]
I'm back from my vacation. Has this been addressed already?

**Comment by kvas-it** [comment]
Hi Andreas,
Unfortunately I have been quite busy in all this time and wasn't able to prioritize this. Still not done, sorry.

**Comment by cryptomilk** [comment]
Any news?

**Comment by kvas-it** [comment]
Hi Andreas!
I have implemented a virtualenv-based solution to this ticket. Could you check if the tests now pass in your environment?
