### ISSUE TITLE
Warnings caused by pytest4

### ISSUE THREAD

**Issue by a96tudor** [kvas-it/pytest-console-scripts#12]
With the update to pytest 4, some changes cause warnings to be risen when using pytest_console_scripts. Here is a dump of the warning:

```
py27/lib/python2.7/site-packages/pytest_console_scripts.py:60: RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
Please use node.get_closest_marker(name) or node.iter_markers(name).
Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
  mark_mode = launch_mode_mark.args[0] if launch_mode_mark else None
```

This can be solved by following the instructions available here:  https://docs.pytest.org/en/latest/mark.html#updating-code

**Comment by kvas-it** [comment]
Thanks, Tudor, I have seen the warnings. This should be solved by [this commit https://github.com/kvas-it/pytest-console-scripts/commit/1687bd7deb879fc5d74012c626a2f47f289ba83a] -- I just need to make a release.

**Comment by kvas-it** [comment]
Version [0.1.6](https://pypi.org/project/pytest-console-scripts/0.1.6/) should fix your issue.

**Comment by a96tudor** [comment]
hey, yeah, it is. Thanks for this!
sorry for the late reply!

**Comment by kvas-it** [comment]
Thanks for the confirmation!
