### ISSUE TITLE
Setup coverage report in tests

### ISSUE THREAD

**Issue by a96tudor** [kvas-it/pytest-console-scripts#16]
Currently, the `Contributing` section from the [README](https://github.com/kvas-it/pytest-console-scripts/blob/master/README.rst#contributing) requires that contributions made the repository to keep the same level of test coverage. There is no coverage report setup in `tox.ini`, though.

In consequence, I suggest we should add this report when running tests.

**Comment by kvas-it** [comment]
Sounds good. Let's do it.
