### ISSUE TITLE
Running as 'inprocess' when using the decorator with 'subprocess' after upgrade to pytest 4.1.0

### ISSUE THREAD

**Issue by alevaquero** [kvas-it/pytest-console-scripts#18]
When trying to run a test as 'subprocess' flagged in the decorator (@pytest.mark.script_launch_mode('subprocess')), the test actually runs as 'inprocess'. This same test worked fine with pytest-4.0.2, but looks got broken after upgrading to pytest-4.1.0. In both cases console-scripts was 0.1.7 and Python 3.4.5.

The workaround for me was to use the pytest command line option --script-launch-mode=subprocess

**Comment by kvas-it** [comment]
Thanks for reporting this. I have also seen this issue a couple of days ago and will work to fix it in the coming days.
