### ISSUE TITLE
set PYTHONHOME instead of PYTHONPATH in test_run_scripts.py

### ISSUE THREAD

**Issue by Kelledin** [kvas-it/pytest-console-scripts#21]
Currently, on Ubuntu (and probably also Debian), everything in test_run_scripts.py bombs with errors similar to the following:

> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
>     [Errno 2] No such file or directory: '/tmp/pytest-of-kelledin/pytest-1/venv0/local/lib/python2.7/dist-packages/test-easy-install-14689.write-test'
> 
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     /tmp/pytest-of-kelledin/pytest-1/venv0/local/lib/python2.7/dist-packages/
> 
> This directory does not currently exist.  Please create it and try again, or
> choose a different installation directory (using the -d or --install-dir
> option).

I managed to get past this problem on my system by removing the `env['PYTHONPATH']` setting, and instead setting `env['PYTHONHOME'] = self.path.strpath`.  This appears to more closely mimic the actions of a virtualenv "activate" script fragment, so I suspect it's the proper thing to do for now.  (To be fair, it would be nice if there was something like a `virtualenv.activate_environment()` method, so we didn't have to guess as to how to activate a virtualenv from within Python code.)

The fact that Debian-based distros use `dist-packages` (and apparently hardcode this into `setup.py develop` usage) probably also had something to do with triggering this error.

**Comment by kvas-it** [comment]
Hey! Thanks for reporting this.

How exactly are you running the tests to trigger the error? I'm on Debian myself and when I run them with Tox everything seems to work fine (or could it be just an Ubuntu thing?).

(Totally agree that it would be nice to have a standard way to activate virtualenvs from Python...)

**Comment by Kelledin** [comment]
I tried invoking tests either via "python setup.py test", or by running "python -m pytest" (within the top-level of the source tree).  Both produced the same error.

(I _may_ have tried it wit PYTHONPATH=$PWD in my environment as well.  My typical test sequence is "python setup.py config && python setup.py build && python setup.py test && python setup.py install".)

I initially noticed this error on a Debian-like custom distro build, then hopped over to an Ubuntu 17.10 system to confirm it wasn't just my environment.  Same error happened in both environments.

**Comment by kvas-it** [comment]
Yeah, I was able to reproduce your behavior when using system python. I always use virtualenvs and in them it works no matter how I run the tests, that why I had a bit of a blind spot here.

Unfortunately your proposed fix breaks the tests under Tox, which is how I normally run them (and how TravisCI runs them). Setting `PYTHONHOME` is not a problem (however, it's actually not needed for system Python to work) but removing `PYTHONPATH` breaks test under Tox (and this one is needed for system Python to work). So I will need to figure out a way to make both approaches workable -- I think it should be possible if we just detect if we are in a virtualenv in the first place or not.

**Comment by kvas-it** [comment]
Can you try the version from the pull request #22 and see if that works? Thank you.

**Comment by kvas-it** [comment]
This ticket has been hanging open for while and as far as I can see #23 fixes the issue so I'm going to merge it unless there's objection. Seems like it's a step forward and if it turns out to be an incomplete fix, we can always follow up with more fixes.
