### ISSUE TITLE
now requires py.test >= 4, I believe?

### ISSUE THREAD

**Issue by ctb** [kvas-it/pytest-console-scripts#26]
I got this error trying out pytest-console-scripts with pytest-3.1 --

```
AttributeError: 'Metafunc' object has no attribute 'definition'
```

which googles to this issue https://github.com/s3ql/s3ql/issues/86. Upgrading to the latest pytest (5.1.2) fixed it.

However, the requirements here, https://pypi.org/project/pytest-console-scripts/, say that pytest-console-scripts needs pytest 3 or above.

**Comment by kvas-it** [comment]
Thanks for catching this, Titus. I can reproduce your failure with pytest-3.1.0. I will update setup.py and the README and release a new version.

**Comment by ctb** [comment]
excellent, thank you!
