### ISSUE TITLE
Add support for passing environment variables to the script under test

### ISSUE THREAD

**Issue by kvas-it** [kvas-it/pytest-console-scripts#3]
It's already possible to do it via simply modifying `os.environ` before running the script and then restoring it but it would be nice if `script_runner.run(...)` had a parameter for that. Actually `run_subprocess` already does: `env` argument will be just passed to `subprocess.Popen` so we just need to implement it for `run_inprocess`.

**Comment by a96tudor** [comment]
I'm on it
