### ISSUE TITLE
Encoding issues under Windows

### ISSUE THREAD

**Issue by brechtm** [kvas-it/pytest-console-scripts#37]
I'm running into a crash related to encoding on Windows:

```
(.venv) C:\Users\Brecht\My Documents\Opqode\rinohtype>pytest tests_regression -k test_version[inprocess]
============================= test session starts =============================
platform win32 -- Python 3.8.6, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: C:\Users\Brecht\My Documents\Opqode\rinohtype, inifile: setup.cfg
plugins: assume-2.2.1, console-scripts-0.2.0
collected 41 items / 40 deselected / 1 selected

..\..\..\My Documents\Opqode\rinohtype\test_rinoh.py F                   [100%]

================================== FAILURES ===================================
___________________________ test_version[inprocess] ___________________________

script_runner = <ScriptRunner inprocess>

    def test_version(script_runner):
        ret = script_runner.run('rinoh', '--version')
>       assert ret.success
E       assert False
E        +  where False = <pytest_console_scripts.RunResult object at 0x000001F1725F7520>.success

C:\Users\Brecht\Documents\Opqode\rinohtype\tests_regression\test_rinoh.py:21: AssertionError
---------------------------- Captured stdout call -----------------------------
# Running console script: rinoh --version
# Script return code: 1
# Script stdout:

# Script stderr:
Traceback (most recent call last):
  File "c:\users\brecht\my documents\opqode\rinohtype\.venv\lib\site-packages\py\_path\common.py", line 177, in read
    return f.read()
  File "C:\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2: character maps to <undefined>

=========================== short test summary info ===========================
FAILED ..\..\..\My Documents\Opqode\rinohtype\test_rinoh.py::test_version[inprocess]
====================== 1 failed, 40 deselected in 1.73s =======================
```
Running `rinoh --version` in the same terminal runs without issues.

I can't seem to figure out how to get a full traceback pointing out the relevant piece of pytest-console-scripts code.

**Comment by kvas-it** [comment]
Hi @brechtm!

It seems that it might be `script.read()` in [this line](https://github.com/kvas-it/pytest-console-scripts/blob/master/pytest_console_scripts.py#L194). Could you modify `pytest-console-scripts` (just in your local installation) to reraise the exception [here](https://github.com/kvas-it/pytest-console-scripts/blob/master/pytest_console_scripts.py#L204): just insert `raise` before this line. Then you will have a more full traceback and we can investigate.

My guess would be that `py.path` fails to read your script (this [line](https://github.com/pytest-dev/py/blob/master/py/_path/common.py#L177)) but I would like to verify that before deciding what to do.

Cheers,
Vasily

**Comment by brechtm** [comment]
Thanks, Vasily. It looks like your guess is correct. This is the relevant part of the traceback wih the `raise` in place:

```
script_runner = <ScriptRunner inprocess>

    def test_version(script_runner):
>       ret = script_runner.run('rinoh', '--version')

tests_regression\test_rinoh.py:20:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ScriptRunner inprocess>, command = 'rinoh', arguments = ('--version',), options = {}

    def run(self, command, *arguments, **options):
        print('# Running console script:', command, *arguments)
        if self.launch_mode == 'inprocess':
>           return self.run_inprocess(command, *arguments, **options)

..\..\code\pytest-console-scripts\pytest_console_scripts.py:126:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ScriptRunner inprocess>, command = 'rinoh', arguments = ('--version',), options = {}
cmdargs = ['rinoh', '--version']
script = local('C:\\Users\\Brecht\\Documents\\Opqode\\rinohtype\\.venv\\Scripts\\rinoh.EXE')
stdin = <_io.StringIO object at 0x000001D95B3FF310>, stdout = <_io.StringIO object at 0x000001D95B3FF5E0>
stderr = <_io.StringIO object at 0x000001D95B3FF670>, returncode = 0
stdin_patch = <mock.mock._patch object at 0x000001D95B3EE100>
stdout_patch = <mock.mock._patch object at 0x000001D95B3EE430>
stderr_patch = <mock.mock._patch object at 0x000001D95B3EE0D0>
argv_patch = <mock.mock._patch object at 0x000001D95B3EE0A0>

    def run_inprocess(self, command, *arguments, **options):
        cmdargs = [command] + list(arguments)
        script = py.path.local(self._locate_script(command, **options))
        stdin = options.get('stdin', StreamMock())
        stdout = StreamMock()
        stderr = StreamMock()
        returncode = 0
        stdin_patch = mock.patch('sys.stdin', new=stdin)
        stdout_patch = mock.patch('sys.stdout', new=stdout)
        stderr_patch = mock.patch('sys.stderr', new=stderr)
        argv_patch = mock.patch('sys.argv', new=cmdargs)
        saved_dir = os.getcwd()
        logger_conf = self._save_and_reset_logger()

        if 'env' in options:
            old_env = os.environ
            os.environ = options.get('env')

        if 'cwd' in options:
            os.chdir(options['cwd'])
        with stdin_patch, stdout_patch, stderr_patch, argv_patch:
            try:
>               compiled = compile(script.read(), str(script), 'exec', flags=0)

..\..\code\pytest-console-scripts\pytest_console_scripts.py:194:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = local('C:\\Users\\Brecht\\Documents\\Opqode\\rinohtype\\.venv\\Scripts\\rinoh.EXE'), mode = 'r'

    def read(self, mode='r'):
        """ read and return a bytestring from reading the path. """
        with self.open(mode) as f:
>           return f.read()

..\..\..\my documents\opqode\rinohtype\.venv\lib\site-packages\py\_path\common.py:177:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <encodings.cp1252.IncrementalDecoder object at 0x000001D95B3EEB50>
input = b'MZ\x90\x00\x03\x00\x00\x00\x04\x00\x00\x00\xff\xff\x00\x00\xb8\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\...\x0b\x01\x00\xb7\xe3\x00\x00\xd0\xe3\x00\x004\x0f\x01\x00\xd0\xe3\x00\x00\x1c\xe4\x00\x000\x10\x01\x00\x00\x00\x00\x00'
final = True

    def decode(self, input, final=False):
>       return codecs.charmap_decode(input,self.errors,decoding_table)[0]
E       UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2: character maps to <undefined>

C:\Python38\lib\encodings\cp1252.py:23: UnicodeDecodeError
------------------------------------------------ Captured stdout call -------------------------------------------------
# Running console script: rinoh --version
=============================================== short test summary info ===============================================
FAILED tests_regression/test_rinoh.py::test_version[inprocess] - UnicodeDecodeError: 'charmap' codec can't decode byt...
========================================== 1 failed, 40 deselected in 3.91s ===========================================
```

**Comment by brechtm** [comment]
I just noticed that the script file is an _exe_ on windows! So of course there will be encoding errors when reading the file contents...

**Comment by brechtm** [comment]
[This patch](brechtm/pytest-console-scripts/commit/8ca02e8cf8f2bd84791c7d7b09c55a700a20649f) fixes this issue, but loads the console script by entry point, breaking all of your tests (which don't seem to test any console scripts installed by entry point).

**Comment by kvas-it** [comment]
Cool! This is better than the entry point loading via finding the installed script that I had before (which doesn't work on Windows).

Regarding the test breaking, my understanding of what's going on is as follows:

- I have recently implemented running of the scripts that are not installed (just a random `.py` file anywhere can now be run via `script_runner`) and this allowed me to simplify the test suite dramatically. Now I don't need to install all those test scripts so I don't need to create another virtualenv inside of the tests. Virtualenv creation involved some fragile hackery to make the libraries from host Python, like pytest, available in the testing virtualenv, and that was complex and also broke sometimes.
- So far so good, but now the test suite depends heavily on running not installed Python scripts (it only checks running installed scripts once by running `pytest`, which we know should be available).
- Your change breaks not installed scripts (because it always invokes things via `console_scripts` entry points), so everything crashes and burns.

I think we can have the cake and eat it too: we could use your patch for loading the entry points, and if that fails, we use the current implementation. Probably the best way to do it is rename `_locate_script` to `_load_script` and make it return a function that loads the entry point if possible or runs the script the old way otherwise.

Do you have any interest in implementing it or should I do it?

**Comment by kvas-it** [comment]
@brechtm: I implemented the idea above: the code in `run_inprocess` looks nice, I like it. Hopefully it also works on Windows 😅.

Please check if the version from #38 works in your use case.

**Comment by brechtm** [comment]
> Do you have any interest in implementing it or should I do it?

After my last comment, I was actually thinking about an implementation along the same lines. You didn't exactly give me enough time to implement this, however 😃 

> Please check if the version from #38 works in your use case.

Look good except a small bug in handling the exit code. It returns `None` on success. You should probably write a test for that ;-)

**Comment by kvas-it** [comment]
> After my last comment, I was actually thinking about an implementation along the same lines. You didn't exactly give me enough time to implement this, however 😃

Yeah indeed, I didn't, sorry. I started looking how to do it and very soon I had a basically working implementation so I decided to just upload it :)

> Look good except for a small bug in handling the exit code. It returns None on success. You should probably write a test for that ;-)

Aha, cool, I'll fix that and yes, seems like a good idea to have a test.

**Comment by kvas-it** [comment]
Fixed the `None` handling and added a test -- it's a bit hacky because it runs `easy_install` to produce the `None`-returning behavior, but I think that should be ok. Unfortunately now that I got rid of the inner virtualenv I can't just install whatever scripts for testing and `pytest` returns `0` on success.

I think your tests should also work now. Thanks for the debugging help!

**Comment by brechtm** [comment]
I didn't know a console script function could return an integer that would be used as a return code, since the [setuptools docs](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html) do not mention this. It is however mentioned in the [PyPA User Guide](https://packaging.python.org/specifications/entry-points/?highlight=console#use-for-scripts).

For your tests, you could [dynamically create entry points](https://stackoverflow.com/a/50789191/438249). This isn't documented, but I reckon it's safe enough for tests.

Thanks!

**Comment by brechtm** [comment]
I just checked, and #38 is working for me now!

**Comment by kvas-it** [comment]
> For your tests, you could dynamically create entry points. This isn't documented, but I reckon it's safe enough for tests.
This is a really cool idea. Of course it's somewhat hacky, but might actually be less hacky than using `easy_install` :D Thanks for this suggestion.

> I just checked, and #38 is working for me now!
Great, I will merge the MR then. And now there's even more reason to finally release version 1.0.0.
