### ISSUE TITLE
Print out return code, stdout and stderr output from the script on error

### ISSUE THREAD

**Issue by kvas-it** [kvas-it/pytest-console-scripts#4]

**Comment by a96tudor** [comment]
Hey! I'd like to work on this. 
I just have a question: what do you mean by "error"? `returncode != 0`?

**Comment by kvas-it** [comment]
Hey! Cool.

By "error" I mean "when the test fails". The idea is that in most cases, when the test fails it's useful to see what the script under test did and what it printed out. I find myself inserting `print(result.stdout)` and `print(result.stderr)` into the test quite often to get this information. It would be nice if pytest-console-scripts did it automatically (and would save me some typing and another test run).

We can actually print those things out all the time -- normally this output would be swallowed by capturing machinery of pytest but if the test fails we would see it.

**Comment by grant-humphries** [comment]
+1 for this feature, this is what I use as a work around the mean time:

```Python
assert result.success, result.stderr
```
