### ISSUE TITLE
PyPI Wheels?

### ISSUE THREAD

**Issue by bollwyvl** [kvas-it/pytest-console-scripts#54]
Thanks for `pytest-console-scripts`!

Would it be possible to get PyPI wheels distributed along with the sdists? As a downstream user, this is nice as it reduces the amount of install-time code that gets executed (e.g. `setup.py`, build systems, etc.)

I've generally taken to generating and hashing the `.tar.gz` and `.whl` packages in CI and archiving them, then actually  uploading them offline, as this does a good job of ensuring no unexpected files/line endings/etc. get introduced, while avoiding the potential damage from credential issues online.

**Comment by kvas-it** [comment]
Thank you for the kind words. Yes, it should be possible to also distribute wheels. I'll look into it.

**Comment by kvas-it** [comment]
I [published](https://pypi.org/project/pytest-console-scripts/#files) a wheel for 1.3.1 (the last version). Let me know if you're also interested in older ones.

**Comment by bollwyvl** [comment]
Newest is fine for me! Thanks so much!
