### ISSUE TITLE
Parity with subprocess.run

### ISSUE THREAD

**Issue by HexDecimal** [kvas-it/pytest-console-scripts#63]
The readme explains that the `console_scripts` fixture works similarly to [subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run). I'd like to make it even more similar so that it's easier to port tests using tools similar to `subprocess.run` and also have it be more obvious how the fixture works.

Specifically I'd like to suggest the following changes:
- Have the first parameter to `script_runner.run` be a sequence similar to how `subprocess.run` works and support giving PathLike objects with arguments.  Something like: `Sequence[str | os.PathLike[str]]`.  Possibly deprecate `*arguments`.
- Deprecate `**options` and add support for keywords by hand.  This is to make it more clear when something isn't actually supported and helps with controlling the input for what is supported.  `**options` breaks type-checking and won't warn on bad parameters.
- Support the `check` keyword.  An exception will be raised for "inprocess" mode on non-zero returns after the debug results are printed.  Possibly raising `subprocess.CalledProcessError` with the appropriate values to mimic `subprocess.run`.
- `shell=True` for "inprocess" can probably be supported with `subprocess.list2cmdline` and [shlex.split](https://docs.python.org/3/library/shlex.html#shlex.split).

`script_runner` should keep the defaults of everything being in Unicode.  I don't want to complicate it with bytes handling.

```py
def test_subprocess_like_args(script_runner):
    # Examples assuming "inprocess" mode.
    result = script_runner.run(['foobar', '--version'], check=True)  # check=True raises if result.returncode is non-zero
    test_script: Path = ...  # Direct path to script.py
    script_runner.run([test_script], check=True)  # Pass a PathLike as an argument
    script_runner.run(test_script, check=True)  # str or PathLike also works as a single direct argument

    script_runner.run("script --test", shell=True, check=True)  # Could be supported in theory.
```

**Comment by kvas-it** [comment]
So you want to support both ways of calling `script_runner.run()` with the same function. This seems more difficult, but yeah, should be possible.

Alright, looking forward to the PR!
