### ISSUE TITLE
Please package tests and the LICENSE file

### ISSUE THREAD

**Issue by cryptomilk** [kvas-it/pytest-console-scripts#8]
Hi,

the pypi package doesn't include the LICENSE file and tests. Could you please add them and also add a test target to setup.sy so you can run the tests correctly.

python setup.py test

This is required to package it for distributions like openSUSE and Fedora.

Thanks!

**Comment by kvas-it** [comment]
@cryptomilk can this be closed now?

**Comment by cryptomilk** [comment]
Yes, if you could push pytest-console-scripts-0.1.5 with the fixes to pypi :-)

**Comment by kvas-it** [comment]
Done. Thanks for your advice!

**Comment by cryptomilk** [comment]
LICENSE file is there and tests can be executed (but fail). Closing
